name: Run tests

on:
  workflow_call:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: npm install
      - name: Run integration tests on sandbox
        run: npm run test
